"""Resend email sender.

Resend is the most ergonomic transactional email API on the market right
now — one HTTP POST, no SMTP, no OAuth dance. Free tier is 100/day or
3,000/month, which is plenty for a demo. The sender domain
``onboarding@resend.dev`` works out of the box without DNS verification.

Used by the deployed Streamlit app to actually deliver the AI-narrated
rate-sheet email to the reviewer's own address. Three guardrails on top
because this lives behind a public URL:

  1. Recipient is locked to the email the user typed in the same session
     (no third-party recipients — the UI enforces this).
  2. A "DEMO" footer is appended so anyone receiving the message knows
     it came from a take-home test, not a real procurement system.
  3. A short per-session send counter (enforced in the Streamlit layer)
     prevents the page from being used as a relay.

If ``RESEND_API_KEY`` is not set, this module is a no-op that returns a
descriptive failure — the rest of the app keeps working (the preview
already shows the email).
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any

import urllib.request
import urllib.error
import json


RESEND_URL = "https://api.resend.com/emails"
DEFAULT_FROM = os.environ.get("RESEND_FROM", "Rate Sheet Demo <onboarding@resend.dev>")

DEMO_FOOTER_HTML = """
<hr style="margin-top:24px;border:none;border-top:1px solid #e5e7eb">
<p style="color:#9ca3af;font-size:11px;font-family:sans-serif;margin-top:8px">
This message was generated by a take-home demo project
(<a href="https://github.com/rmptue/rate-sheet-diff-agent" style="color:#9ca3af">github.com/rmptue/rate-sheet-diff-agent</a>).
You are receiving it because you entered your address into the demo's
"Email this to me" field. No follow-up emails will be sent. Not a real
freight rate notification.
</p>
""".strip()


@dataclass
class ResendResult:
    ok: bool
    detail: str
    message_id: str | None = None


def send_via_resend(subject: str, html: str, recipient: str,
                    sender: str | None = None) -> ResendResult:
    """POST one email through Resend. Returns a ``ResendResult``.

    Network and API errors are caught so the UI can show a clean message
    rather than crashing the page.
    """
    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        return ResendResult(False, "RESEND_API_KEY not configured on the server.")

    payload = {
        "from": sender or DEFAULT_FROM,
        "to": [recipient],
        "subject": subject,
        "html": html + DEMO_FOOTER_HTML,
    }

    req = urllib.request.Request(
        RESEND_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            body: dict[str, Any] = json.loads(resp.read().decode("utf-8"))
            return ResendResult(True, f"Sent to {recipient}", message_id=body.get("id"))
    except urllib.error.HTTPError as e:
        raw = ""
        try:
            raw = e.read().decode("utf-8", errors="replace")
        except Exception:
            raw = ""
        # Resend returns JSON like {"statusCode": 403, "name": "validation_error",
        # "message": "You can only send testing emails to your own email ..."}.
        # Extract the human message no matter how it's nested.
        msg = e.reason or "Forbidden"
        try:
            body = json.loads(raw)
            msg = (body.get("message")
                   or body.get("error")
                   or (body.get("error", {}).get("message") if isinstance(body.get("error"), dict) else None)
                   or raw[:300]
                   or msg)
        except Exception:
            if raw:
                msg = raw[:300]
        return ResendResult(False, f"Resend {e.code}: {msg}")
    except urllib.error.URLError as e:
        return ResendResult(False, f"Network error reaching Resend: {e.reason}")
    except Exception as e:  # noqa: BLE001
        return ResendResult(False, f"Unexpected error: {type(e).__name__}: {e}")
